### ISSUE TITLE
Add option to bypass checksum verification in verify mode

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/omSipCreator#56]
Why:  checksum verification can be time-consuming, and is done at write-time anyway. So in some cases it might be preferrable to skip this at the verify stage.

**Comment by kieranjol** [comment]
I think I've done something similar, disabling hash checks in dfxml scripts
sometimes, or skipping checksum generation when generating a PREMIS XML if
a manifest sidecar is detected - the PREMIS XML gets populated with values
pulled from the manifest..

**Comment by bitsgalore** [comment]
Done: <https://github.com/KBNLresearch/omSipCreator/issues/56>
